### PR TITLE
Allison Foster index calculation implementation

### PR DESCRIPTION
**Pull request by Reckony**
Implementation of issue https://github.com/hs3city/ordinal-scale-stats-py/issues/14

### CODE REVIEW

**Review by fgrabowski — CHANGES_REQUESTED** [review]
Submitted code would not pass through python's Black formatting on which I am working on right now to run workflows while opening a PR. What I'd recommend for you to do is install black through `pip install black` command and then execute `black <file_name>` on both files. However, the only issue I saw is no blank line at the end of the files.

**Review by fgrabowski — CHANGES_REQUESTED** [review]
Also, If we are taking an src package structure approach, shouldn't the code provided on this PR be inside of src/ folder? Correct me @SimonMolinsky if i'm wrong

**Review by fgrabowski — COMMENTED** [review]
Also, would you be able to run `poetry install` and `pip install poetry` on your computer if you don't have it yet, after resolving previous requests in order to create a poetry.lock file and allow us to manage current dependencies?

**Comment by fgrabowski** [comment]
> Submitted code would not pass through python's Black formatting on which I am working on right now to run workflows while opening a PR. What I'd recommend for you to do is install black through `pip install black` command and then execute `black <file_name>` on both files. However, the only issue I saw is no blank line at the end of the files.

Okay, tests will be running on PRs from now.

**Comment by Reckony** [comment]
All comments were addressed

**Review by fgrabowski — APPROVED** [review]

**Comment by SimonMolinsky** [comment]
I'm checking the function's logic and give you some feedback.

**Comment by SimonMolinsky** [comment]
Thank you @Reckony !

Comments from me: in general, everything is fine! We could pass PR as it is! However, we can make our future brighter when we change little pieces of your code :) 

I propose to use the `numpy` and `scipy` instead of the `statistics` module. Then, `numpy` **median** and **mean** functions should be used in the `compute_measures` function.

- [ ] instead of `typing.List` use `typing.Iterable`,
- [ ] add `numpy` and `scipy` to dependencies,
- [ ] use: https://numpy.org/doc/stable/reference/generated/numpy.mean.html and https://numpy.org/doc/stable/reference/generated/numpy.median.html to calculate mean and median.

**Review by SimonMolinsky — APPROVED** [review]

**Review by fgrabowski — APPROVED** [review]

**Pull request merged**
